# This workflow can be used to publish any gradle project in the repo
name: Publish Gradle Project

on:
  workflow_dispatch:
    inputs:
      project:
        description: 'The project to publish'
        type: string
  workflow_call:
    inputs:
      project:
        description: 'The project to publish'
        type: string

jobs:
  publish_gradle:
    name: Publish Gradle
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4

      - name: Ensure Wrapper Permissions
        run: chmod +x ./gradlew

      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Gradle Publish
        uses: gradle/gradle-build-action@v2
        env:
          CI: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          arguments: "${{inputs.project && format('{0}:', inputs.project)}}publish --scan"

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: gradle-build
          path: '**/build/libs/*'
